### ISSUE TITLE
Display Deploy info on BlockExplorer

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-network/casper-blockexplorer#105]
looking for a list of deploys, rather than depending on the deploy hash for display

**Comment by hoffmannjan** [comment]
@RitaMAllenCA this is both `middleware` and `frontend` ticket. 
So this requires three tickets:
- Design view containing list of deploys (`frontend`) cc: @megan-demit 
- Implement view containing list of deploys (`frontend`)
- Implement middleware endpoint for `/deploys` (`middleware`)

**Comment by RitaMAllenCA** [comment]
Issue moved to [casper-network/casper-blockexplorer-middleware #1](https://github.com/casper-network/casper-blockexplorer-middleware/issues/1) via [**Zenhub**](https://www.zenhub.com/)
