### ISSUE TITLE
Block Explorer home screen UI redesign

### ISSUE THREAD

**Issue by megan-demit** [casper-network/casper-blockexplorer#107]
Redesign home screen based on discussed revisions 

Related to [issue 98](https://github.com/casper-network/casper-blockexplorer/issues/98)

**Comment by megan-demit** [comment]
@hoffmannjan @Thistle-Strum @valfaro123 @DorianKwan [edits here](https://www.figma.com/file/GS7thHuVvP72ZrnBkWrVAp/block-explorer?node-id=0%3A1&t=8Db3MtreGntq76QY-1)
I changed the font size of the boxes on the home screens, the top nav on the web screens, and added the second screen option for subsequent visits to the site. There are some notes in the file.

**Comment by caspersteve** [comment]
Awesome work @megan-demit !
