### ISSUE TITLE
Refactor Project Structure

### ISSUE THREAD

**Issue by gyroflaw** [casper-network/casper-blockexplorer#112]
TODO List:
- [ ] Revert `react-scripts reject` commit and add [react-app-rewired](https://www.npmjs.com/package/react-app-rewired) to polyfill modules.
- [ ] Remove some modules
    - [ ] `react-use-measure`
- [ ] Update redux usage following @reduxjs/toolkit typescript [guide](https://redux-toolkit.js.org/usage/usage-with-typescript)
- [ ] Use GitHub workflow for CI

**Comment by hoffmannjan** [comment]
@gyroflaw I moved part of this ticket to another one and assigned to @Thistle-Strum 
https://github.com/casper-network/casper-blockexplorer/issues/116

**Comment by hoffmannjan** [comment]
>Revert react-scripts reject commit and add [react-app-rewired](https://www.npmjs.com/package/react-app-rewired) to polyfill modules.
- this is questionable, already tackled this with @DorianKwan 

>  Remove some modules: react-use-measure
Why do you want to remove it ? 

> Update redux usage following @reduxjs/toolkit typescript [guide](https://redux-toolkit.js.org/usage/usage-with-typescript)

What's wrong with the current usage ? ☺️ 

> Use GitHub workflow for CI
- We can't because our company rely on Harness.io

**Comment by gyroflaw** [comment]
> Remove some modules: react-use-measure

This has already been discussed with @DorianKwan.

> Redux

Current usage is good so far, except for selectors. I think since we added typed [useAppSelector](https://github.com/casper-network/casper-blockexplorer/blob/3f00e48899a4b248a31c66b23f318bbf4f5d4b7c/frontend/src/store/hooks.ts#L5), accessing redux can be easy as below

```typescript
const { bounds } = useAppSelector(state => state.app);
```

without using these [selectors](https://github.com/casper-network/casper-blockexplorer/blob/3f00e48899a4b248a31c66b23f318bbf4f5d4b7c/frontend/src/store/selectors/index.ts#L1-L4).

I think the current approach doesn't meet these [rules](https://www.boldare.com/blog/kiss-yagni-dry-principles/).

> GitHub CI

By using GitHub CI, the PR author can be noticed what things going on in CI and where he made the issues **without leaving GitHub** like [this](https://github.com/casper-network/casper-blockexplorer/actions/workflows/ci-middleware.yml). I saw some of our repositories are planning to migrate CI to GitHub
