### ISSUE TITLE
Improve how we handle refresh in blocks cache

### ISSUE THREAD

**Issue by hoffmannjan** [casper-network/casper-blockexplorer#127]
~~There is one thing that can be improved - now we have a fixed refresh interval, but it should be calculated based on `getStatus()` -> `last_added_block_info.timestamp`.
So if the timestamp is eg. `2023-01-05T13:47:41.952Z` we should refresh our data in
`2023-01-05T13:47:41.952Z + PEERS_UPDATE_INTERVAL`, so when it's set to eg 40s we know when revalidate the cache. The timestamp should be taken into consideration after every refresh.~~

Please do the same that was described above, but for `blocks`. So treat `timestamp` as a source of truth and calculate when approx. new block will be emitted.

**Comment by hoffmannjan** [comment]
@gyroflaw please estimate when you'll have free time

**Comment by hoffmannjan** [comment]
Hi @gyroflaw , in terms of `peers` I think we will need to re-discuss this. 
But you can use the same rule for the `blocks`, shouldn't be a problem, right? 

For now please stop working on `peers`, there might be some bigger changes.

**Comment by hoffmannjan** [comment]
I renamed the ticket accordingly.

**Comment by hoffmannjan** [comment]
@RitaMAllenCA this is `middleware` ticket

**Comment by RitaMAllenCA** [comment]
moved to new repo
