### ISSUE TITLE
Start building Event Store in BlockExplorer middleware

### ISSUE THREAD

**Issue by hoffmannjan** [casper-network/casper-blockexplorer#128]
So let's start in BE middleware but please keep in mind that we might want / need to treat eventstore as separate service later.

As a base functionalities it should be able to:
- store past deploys
- search through past deploys
- also act as a cache for most recent data (peers and validators)

**Comment by hoffmannjan** [comment]
This will be probably postponed due to SSE Sidecar functionalities.

**Comment by hoffmannjan** [comment]
@RitaMAllenCA this is `middleware` ticket - but TBD (probably we can close it as we will rely on sidecar).

**Comment by RitaMAllenCA** [comment]
Closing this as we expect to rely on sidecar. If it turns out we can not we will open a new ticket in the middleware repo
