### ISSUE TITLE
Add new way of showing peers

### ISSUE THREAD

**Issue by hoffmannjan** [casper-network/casper-blockexplorer#136]
So we will need to use middleware `GET /peers` endpoint and display the appropriate data in the `Peers view`

**Comment by RitaMAllenCA** [comment]
@hoffmannjan do we need to have the sidecar do anything to support this?  LMK so I can create a ticket

**Comment by hoffmannjan** [comment]
nope, we can do this for `1.1` only using RPC and this is preferable way of doing this :) in fact I already did this ;)

**Comment by hoffmannjan** [comment]
Added this in [this PR](https://github.com/casper-network/casper-blockexplorer/pull/137)
<img width="1840" alt="Screenshot 2023-01-24 at 15 50 48" src="https://user-images.githubusercontent.com/3756160/214326590-dadbd5e2-2176-4274-b54a-6b7be8ad22ea.png">
