### ISSUE TITLE
Make spacing configurable to support branding 

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-network/casper-blockexplorer#139]
Allow spacing to be configurable and document how to use the settings.

**Comment by hoffmannjan** [comment]
@RitaMAllenCA this is `frontend` ticket - but TBD

**Comment by RitaMAllenCA** [comment]
Issue moved to [casper-network/casper-blockexplorer-frontend #4](https://github.com/casper-network/casper-blockexplorer-frontend/issues/4) via [**Zenhub**](https://www.zenhub.com/)
