### ISSUE TITLE
Fix the issue with 404 on specific paths

### ISSUE THREAD

**Issue by hoffmannjan** [casper-network/casper-blockexplorer#166]
So when you refresh or send somebody the link to `/blocks` you get 404 from nginx.

**Comment by hoffmannjan** [comment]
@rob-casper can move it to production and confirm that it works :).

Cheers

**Comment by rob-casper** [comment]
@hoffmannjan - I can hit the button ✅

**Comment by rob-casper** [comment]
can confirm it works, checked

https://explorer.mainnet.casperlabs.io/blocks
https://explorer.chengduchain.com/blocks
