### ISSUE TITLE
Fix the issue with changing order by height

### ISSUE THREAD

**Issue by hoffmannjan** [casper-network/casper-blockexplorer#175]
So when we click to `sort by height` there is a short (or longer, depending on the RPC performance) moment when it changes the order of already downloaded blocks and then after few seconds it shows correctly sorted data (so starting from block 1).

The issue is visible on the video. I know this happens because of the fetch time, but we should show some spinner instead of changing the order of the visible blocks.

https://user-images.githubusercontent.com/3756160/217575546-31afbe60-0d5f-4635-bb5c-59083afa689c.mov

**Comment by mgibson-casper** [comment]
Fixed in: https://github.com/casper-network/casper-blockexplorer-frontend/issues/180
