### ISSUE TITLE
Refactor the frontend

### ISSUE THREAD

**Issue by hoffmannjan** [casper-network/casper-blockexplorer#176]
Do an analysis of the BlockExplorer front end and identify components that can be reused.  Then create reusable components and restructure the block explorer to use these components.

**Comment by RitaMAllenCA** [comment]
@mgibson-casper @DorianKwan @hoffmannjan Hi - as we embark on the creation of our component library, lets set a milestone to pause after the first set of components has been identified in the BE FE and plan a roadmap.  Our process calls for 6-week release cadences.

**Comment by RitaMAllenCA** [comment]
Issue moved to [casper-network/casper-ui-kit #1](https://github.com/casper-network/casper-ui-kit/issues/1) via [**Zenhub**](https://www.zenhub.com/)

**Comment by RitaMAllenCA** [comment]
Issue moved to [casper-network/casper-ui-kit #2](https://github.com/casper-network/casper-ui-kit/issues/2) via [**Zenhub**](https://www.zenhub.com/)
