### ISSUE TITLE
SPIKE:  Research NFT Selfie and identify refactoring opportunities

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-network/casper-blockexplorer#186]
NFT selfie was done under time duress, so it is worth another look to be refactored.  The deliverable is a list of possible areas where refactoring would be a value-add

**Comment by valfaro123** [comment]
- Most of the components in the repo are still being built with tailwind and some are not using typescript so it is probably best to use other projects for the ui kit. 
- The photo/video capture might be useful if we need that for another app down the road but I believe it would be easier to outright build another one if the use case comes up.
- After talking with the rest of the team, the best strategy would be to recreate the app using the ui kit when it is ready.
