### ISSUE TITLE
Block explorer UI edit: pagination

### ISSUE THREAD

**Issue by megan-demit** [casper-network/casper-blockexplorer#188]
Add pagination to both block and peer tables, but not filters

**Comment by megan-demit** [comment]
<img width="641" alt="pagination component" src="https://user-images.githubusercontent.com/102996538/220489800-106c8def-0a75-4e25-b9ae-e1638e0f27cd.png">
*draft* pagination component for blocks and deploys pages

**Comment by megan-demit** [comment]
https://user-images.githubusercontent.com/102996538/220489888-9b89b0a0-b735-483f-9584-3e33fd8b6fdf.mov
pagination on the deploys page. also implemented on the blocks page. not fully fleshed out, but gives you an idea of what it would look like.

ready for review @hoffmannjan

**Comment by hoffmannjan** [comment]
thx Megan, looks great, closing it!
