### ISSUE TITLE
Block explorer UI edit: buttons

### ISSUE THREAD

**Issue by megan-demit** [casper-network/casper-blockexplorer#190]
Make a selected state for the nav bar buttons

**Comment by megan-demit** [comment]
<img width="501" alt="new nav component" src="https://user-images.githubusercontent.com/102996538/220485196-90c127a9-b1ed-4b3a-8246-8b60bb33e6bf.png">
new component for the nav bar

**Comment by megan-demit** [comment]
https://user-images.githubusercontent.com/102996538/220485243-892205e6-4104-44fe-ac25-5f64b33b412f.mov

@hoffmannjan et al, take a look and see what you think of this. it's very easy to change colors if you want

**Comment by hoffmannjan** [comment]
@megan-demit great work!

**Comment by RitaMAllenCA** [comment]
@hoffmannjan this seems generic enough that it could be part of the ui-kit.... WDYT?
