### ISSUE TITLE
Research refactoring opportunities in Factoring Repo

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-network/casper-blockexplorer#195]

**Comment by Thistle-Strum** [comment]
Create Base components and tests for all common input types:

-`<input type="checkbox">` 
    Currently exists in Factoring.  Requires tests and refactoring
![checkbox.png](https://images.zenhubusercontent.com/62ea8c136a2a38241576a01c/65293100-ffc9-4eeb-98b5-e6270bae168d)

-`<input type="password">`
    Currently exists in Factoring.  Requires tests and refactoring
![password.png](https://images.zenhubusercontent.com/62ea8c136a2a38241576a01c/0a3a756c-f55c-4665-ab69-a0ea7e6a0abe)

-`<input type="radio">`
    Currently exists in Factoring.  Requires tests and refactoring
![radio.png](https://images.zenhubusercontent.com/62ea8c136a2a38241576a01c/0afa0f01-e7a0-4f0f-8c9d-989f43657a07)

-`<input type="text">` 
    Currently exists in Factoring.  Requires tests and refactoring
![text.png](https://images.zenhubusercontent.com/62ea8c136a2a38241576a01c/bcfb71b3-8c16-426a-bfb4-1fe933b33ead)

-`<input type="email">`
![email.png](https://images.zenhubusercontent.com/62ea8c136a2a38241576a01c/9b663a6b-d83f-41a3-934a-80e645dc85db)

-`<input type="number">`
Currently only default styles

Additions to existing base Button component:  
-Add React <Link> as an optional type

@hoffmannjan 
@megan-demit

**Comment by RitaMAllenCA** [comment]
@hoffmannjan should this work be here or in the ui-kit?  I can make this an epic and each of these items a separate issue.  Let me know
