### ISSUE TITLE
Block explorer UI edit: create validators page

### ISSUE THREAD

**Issue by megan-demit** [casper-network/casper-blockexplorer#200]
We decided we're going to have a separate validators and connected peers page; we currently only have a connected peers page that it called "validators". 

Create a page solely for validators.

**Comment by megan-demit** [comment]
ready for review @hoffmannjan. this is basically exactly like what is in cspr.live, but it's a decent enough set up and we can modify from here.
![validators](https://user-images.githubusercontent.com/102996538/221021757-749a21bb-c39e-4a9b-a519-cd118ea92db7.png)

**Comment by hoffmannjan** [comment]
For now we will miss `Validator Name` because we don't have a list like this... But otherwise looking fresh 👍
