### ISSUE TITLE
SPIKE: Check reset.css to improve browsers compatibility 

### ISSUE THREAD

**Issue by hoffmannjan** [casper-network/casper-blockexplorer#204]

**Comment by Thistle-Strum** [comment]
@hoffmannjan 
The CSS snippets available at https://www.npmjs.com/package/reset-css
do not resolve the BlockExplorer logo padding discrepancies between Firefox and Firefox Developer Edition browsers.  
However, the padding issue will be resolved once a new BlockExplorer logo SVG is selected to replace the current placeholder logo.

**Comment by Thistle-Strum** [comment]
@hoffmannjan 
The CSS snippets available at https://www.npmjs.com/package/reset-css
do not resolve the BlockExplorer logo padding discrepancies between Firefox and Firefox Developer Edition browsers.  
However, the padding issue will be resolved once a new BlockExplorer logo SVG is selected to replace the current placeholder logo.
