### ISSUE TITLE
Block explorer UI: skeleton loaders

### ISSUE THREAD

**Issue by megan-demit** [casper-network/casper-blockexplorer#207]
Create loading screens for block explorer

**Comment by megan-demit** [comment]
https://user-images.githubusercontent.com/102996538/221286975-ff4f84b8-51ed-4243-a0df-331a8faccd64.mov

this is one of the screens. @hoffmannjan ready for review

**Comment by hoffmannjan** [comment]
@mgibson-casper ☝️ we happy ? ☺️ 
![1639976608150](https://user-images.githubusercontent.com/3756160/221296538-5a8ccd27-c6ee-4f37-8027-10530ab3a5f5.gif)

**Comment by mgibson-casper** [comment]
Amazing! We are definitely happy ;)
