### ISSUE TITLE
Not an issue but is this live somewhere already?

### ISSUE THREAD

**Issue by GuybrushX** [casper-network/casper-blockexplorer#270]
I discovered this repo a few weeks ago and wondered if it is online somewhere already to have a look what you're building here?

Would be much easier than setting everything up myself ;-)

**Comment by hoffmannjan** [comment]
Hi @GuybrushX here is the most common build from `dev` branch :)
https://staging.explorer.mainnet.casperlabs.io/

**Comment by hoffmannjan** [comment]
I'll close this ticket as I believe your question was answered. If you will have any more questions please reopen this ticket.
