### ISSUE TITLE
Fix the Peers page Cypress test

### ISSUE THREAD

**Issue by hoffmannjan** [casper-network/casper-blockexplorer#313]

**Comment by DorianKwan** [comment]
@hoffmannjan The peers Cypress test is not currently failing.  But, the test is very simple.  Should be close this ticket and open another to add more useful tests?

**Comment by hoffmannjan** [comment]
> @hoffmannjan The peers Cypress test is not currently failing. But, the test is very simple. Should be close this ticket and open another to add more useful tests?

yeah please do it!
