### ISSUE TITLE
SPIKE Look for optimal solution for Redux & websockets

### ISSUE THREAD

**Issue by hoffmannjan** [casper-network/casper-blockexplorer#314]
After a brief check it looks like its a common practice to add custom middleware to redux to handle websockets actions.
The aim of this task is to make sure it is true and if so to design how it should work

**Comment by hoffmannjan** [comment]
Depending on the outcome please add another tickets to this epic

**Comment by mgibson-casper** [comment]
It has been determined that we will be able to implement web sockets in the frontend using the sockets-io library out of the box. Tickets to follow.
