### ISSUE TITLE
Blocks Page Tests

### ISSUE THREAD

**Issue by hoffmannjan** [casper-network/casper-blockexplorer#365]
As mentioned in [this PR](https://github.com/casper-network/casper-blockexplorer-frontend/pull/364) we should extend this tests suite.

**Comment by DorianKwan** [comment]
Moving this ticket back to backlog to work on another that's higher priority.  #165

**Comment by hoffmannjan** [comment]
We can even reassign for @valfaro123 or @Thistle-Strum
