### ISSUE TITLE
Create Design for BE 404 Page

### ISSUE THREAD

**Issue by DorianKwan** [casper-network/casper-blockexplorer#366]
The Block Explorer's Error / 404 page is currently still using the old design and is not out-of-date.  This ticket is to create a basic design that matches our new theme

**Comment by megan-demit** [comment]
take a look and see what you think: https://www.figma.com/file/GS7thHuVvP72ZrnBkWrVAp/block-explorer?type=design&node-id=1102%3A1794&t=4TlXI9wQ1LEI8A04-1
