### ISSUE TITLE
Configurable autorefresh interval

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-network/casper-blockexplorer#99]
autorefresh to stop after some time (to stop pinging the server) stretch - make refresh time configurable RYO, 3

**Comment by gyroflaw** [comment]
This issue can be easily done by using [@tanstack/query](https://tanstack.com/query/v4) (also needs some migrate from RTK Query to it) and it was added [here](https://github.com/casper-network/casper-blockexplorer/pull/119).
